fispy/urls.py
from django.conf.urls import url
from django.contrib import admin
from events import views
from graduators import views

#for static root upload
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    #url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),

    url(r'^fispy/$', views.home, name='home'),

    #the error loading events view,was solved by assigning a view called
    #event in views of graduator app
    url(r'^events/$', views.newname2, name='event'),

    #/graduators/      (all graduators are listed)
    url(r'^graduators/$' , views.newname, name='graduator'),

    # /graduators/001  (single detailed response of individual graduator)
    url(r'^graduators/(?P<graduator_id>[0-9]+)/$', views.details, name='detail')
]

if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

events/models.py
from django.db import models

# Create your models here.
class event(models.Model):
    Name=models.CharField(max_length=50,null=True)
    Description=models.TextField(max_length=500,null=True)
    eventDate=models.DateTimeField(max_length=50,null=True)
    eventVenue=models.CharField(max_length=50,null=True)
    eventFee=models.CharField(max_length=50,null=True)


    def  __str__(self):
        return self.Name

graduators/models.py
from django.db import models

# Create your models here.
class graduator(models.Model):
    #memberid==pk
    FullName = models.CharField(max_length=20,null=True)
    PersonalDescription = models.TextField(max_length=200,null=True)
    age = models.CharField(max_length=20,null=True)
    image = models.FileField(max_length=200,null=True)
    email = models.CharField(max_length=30,null=True)
    phone = models.CharField(max_length=30,null=True)
    adress = models.CharField(max_length=30,null=True)
    HighestEducation=models.CharField(max_length=30,null=True)
    graduationYear = models.CharField(max_length=30,null=True)
    Employed = models.BooleanField(default=False)
    #skills in form of tags
    #

    #string representation of the models
    def  __str__(self):
        return self.FullName
        #return self.FirstName + ' - ' + self.LastName

class portfolio(models.Model):
    #'Memberid==fk
    graduator = models.ForeignKey(graduator, on_delete=models.CASCADE)
    projectTitle = models.CharField(max_length=100,null=True)
    projectDescription = models.TextField(max_length=200,null=True)
    projectScreenshot = models.CharField(max_length=200,null=True)
    projectlink = models.CharField(max_length=200,null=True)
    certificationImage = models.CharField(max_length=200,null=True)

    def __str__(self):
        return self.projectTitle

class internshipExperience(models.Model):
    graduator = models.ForeignKey(graduator, on_delete=models.CASCADE)
    institution = models.CharField(max_length=100,null=True)
    position = models.CharField(max_length=100,null=True)
    roles = models.TextField(max_length=100,null=True)

    def __str__(self):
        return self.institution

events/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def event(request):
    return HttpResponse("<h1>List of events will be here</h1>")

graduators/views.py
#these imports support the shortcut approach whic uses render compacted with template pull and HttpResponse
from django.shortcuts import render
from django.http import Http404

#these imports support the good ol way of loader and templates seen in def newname2 rendering events
from django.http import HttpResponse
from django.template import loader

from graduators.models import graduator
from events.models import event
# Create your views here.
#this view has got bugs
def home(request):
    return render(request, "fispy/index.html")

def newname(request):

    all_graduators = graduator.objects.all()
    context = { 'all_graduators' : all_graduators, }
    return render(request, 'graduators/graduatorsmanifest3.html',context )

def details(request, graduator_id):
    try:
        kaka = graduator.objects.get(id=graduator_id)

    except Exception as e:
        raise Http404("That Graduator does not exist")
    return render(request, 'graduators/graduatordetails.html', { 'kaka': kaka })

    '''1.create variable to hold the db result.kaka = graduator.objects.get(pk=graduator_id)
       2.load template = loader.get_template('graduators/graduatordetails.html')
    context = { 'kaka' : kaka }
    return HttpResponse(template.render(context, request))
    '''

def newname2(request):
        all_events = event.objects.all()
        template = loader.get_template('eventpage/eventmanifest.html')
        context = { 'all_events' : all_events, }
        return HttpResponse(template.render(context, request))

events/templates/eventpage/cards.event/eventcard.html
<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
<div class="container profile">
  <div class="row">
    <div class="span12">
      <div class="well well-small clearfix">
        <div class="row-fluid">
          <div class="span2">
             <img src="http://www.gravatar.com/avatar/f6112e781842d6a2b4636b35451401ff?s=125" class="img-polaroid"/>
          </div>
          <div class="span4">
             <h2>Jonnie Spratley</h2>
            <ul class="unstyled">
              <li><i class="icon-phone"></i> 916-241-3613</li>
              <li><i class="icon-envelope"></i> jonniespratley@me.com</li>
              <li><i class="icon-globe"></i> http://jonniespratley.me</li>
            </ul>
          </div>
          <div class="span6">
          <ul class="inline stats">
               <li>
                 <span>275</span>
                 Friends
              </li>
              <li>
                 <span>354</span>
                 Followers
              </li>
               <li>
                 <span>186</span>
                 Photos
              </li>
          </ul>
            <div><!--/span6-->
            </div><!--/row-->
      </div>
      <!--Body content-->
    </div>
  </div>

            <div class="well clearfix">



              <img class="pull-right" src="http://kcdn3.klout.com/static/images/developers/dev-assets/powered-by-klout.png" width="150px"/>
            </div>
</div>

events/templates/eventpage/cards.event/eventcard1.html
<link href="bootstrap-combined.no-icons.min.css" rel="stylesheet">
<link href="font-awesome.css" rel="stylesheet">
<link href="eventcard.css" rel="stylesheet">
<div class="container profile">
  <div class="row">
    <div class="span12">
      <div class="well well-small clearfix">
        <div class="row-fluid">
          <div class="span2">
             <img src="http://www.gravatar.com/avatar/f6112e781842d6a2b4636b35451401ff?s=125" class="img-polaroid"/>
          </div>
          <div class="span4">
             <h2>Jonnie Spratley</h2>
            <ul class="unstyled">
              <li><i class="icon-phone"></i> 916-241-3613</li>
              <li><i class="icon-envelope"></i> jonniespratley@me.com</li>
              <li><i class="icon-globe"></i> http://jonniespratley.me</li>
            </ul>
          </div>
          <div class="span6">
          <ul class="inline stats">
               <li>
                 <span>275</span>
                 Friends
              </li>
              <li>
                 <span>354</span>
                 Followers
              </li>
               <li>
                 <span>186</span>
                 Photos
              </li>
          </ul>
            <div><!--/span6-->
            </div><!--/row-->
      </div>
      <!--Body content-->
    </div>
  </div>

            <div class="well clearfix">



              <img class="pull-right" src="http://kcdn3.klout.com/static/images/developers/dev-assets/powered-by-klout.png" width="150px"/>
            </div>
</div>

events/templates/eventpage/eventmanifest.html
<!--  Header
<div class="container-fluid">

    <header>
        <nav class="navbar container-fluid">
            <div class="container-fluid">
                  <div class="navbar-header">
                      <span class="navbar-brand"><a href="">FISPY</a></span>
                  </div>

                  <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Graduator</a></li>
                    <li><a href="#">Event</a></li>
                    <li><a href="#">Sign in	</a></li>
                  </ul>
            </div>
        </nav>
    </header>
  </div>

<a href="http://127.0.0.1:8000/admin/events/event/add/">Add event</a>

-->
{% load staticfiles %}

<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
<link href="{% static 'eventpage/bootstrap-combined.no-icons.min.css' %}" rel="stylesheet">
<link href="{% static 'eventpage/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'eventpage/eventcard.css' %}" rel="stylesheet">
<div class="container profile">

      {% for event in all_events %}
  <div class="row">
    <div class="span12">
      <div class="well well-small clearfix">
        <div class="row-fluid">
          <div class="span2">
             <img src="" class="img-polaroid"/>
          </div>
          <div class="span4">
             <h2>{{event.Name}}</h2>
            <ul class="unstyled">
              <li><i class="icon-globe"></i> <b>{{event.eventVenue}}</b> </li>
              <li><i class="icon-phone"></i> organizerphone</li>
              <li><i class="icon-envelope"></i> organizeremail</li>
              <li><i class="icon-globe"></i> <a href="http://suza.ac.tz">Organizer website</a></li>
            </ul>
          </div>
          <div class="span6">
          <ul class="inline stats">
               <li> <b><span>  {{event.eventDate}}</span> </b> Event Date </li>
               <!--<li> <span>50</span> Seats </li> -->
               <li> <span>{{event.eventFee}}</span> Fees </li>
          </ul>

            <div><!--/span6-->
            {{event.Description}}
            </div><!--/row-->
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
      <!--Body content-->
    </div>
  </div>
  </div>
</div>
<hr>
{% endfor %}

graduators/templates/fispy/index.html
<!DOCTYPE html>
{% load staticfiles %}
		<html>
				<head>
					<link rel="stylesheet" type="text/css" href="{% static 'homepage/bootstrap/bootstrap.min.css' %}">
					<link rel="stylesheet" type="text/css" href= "{% static 'homepage/index.css' %}" >
					<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
				</head>
				<body>
							<div class="container-fluid">

									<header>
											<nav class="navbar container-fluid">
										  		<div class="container-fluid">
										  					<div class="navbar-header">
											  						<span class="navbar-brand">GradNet</span>
																</div>

																<ul class="nav navbar-nav navbar-right">
												  				<li><a href="http://127.0.0.1:8000/graduators">Graduator</a></li>
												  				<li><a href="http://127.0.0.1:8000/events">Event</a></li>
												  				<li><a href="http://127.0.0.1:8000/admin">Sign in	</a></li>
																</ul>
										  		</div>
											</nav>
									</header>

		<br>
			<section class=" container-fluid">
				<center>
					<article>
							<div class="row logo container-fluid">
									<div class="col-lg-8">
											<img src="{% static 'homepage/image/logo.png' %} ">
									</div>
									<div class="col-lg-4">
											<br>
											<p><input type="email" name="email" placeholder="Enter Fullname"  class="form-control"></p>
											<p><input type="texr" name="username" placeholder="Enter Your Email"  class="form-control"></p>
											<p><input type="password" name="password" placeholder="Password" class="form-control"></p>
											<p><input type="submit" name="btnReg" value="Sign Up" id="btnReg" class="form-control"></p>
									</div>
							</div>
					</article>
				</center>
					<div class="jumbotron display">
							<p>Hello Graduate, This will keep you Active for the time you are noy yet Employed, So if you think you are:</p>
							<div class="row">
							<center>
									<div class="col-lg-4">
											<img src="{% static 'homepage/image/i2.png' %}">
											<div>Productive</div>
									</div>
									<div class="col-lg-4">
											<img src=" {% static 'homepage/image/i1.png' %}">
											<div>Organized</div>
									</div>
									<div class="col-lg-4">
											<img src="{% static 'homepage/image/i3.png' %}">
											<div>Reliable</div>
									</div>
							</center>
							</div>
					</div>
			</section>
			<footer>
					<nav class="navbar navbar-fixed-bottom" >
						  <span>SUZA DIT Final Year Project 2017</span>
						  <div class="about">
								  <span> <a href="#"> Contact </a> </span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
								  <span> <a href="#"> About </a> </span>
						  </div>
					</nav>
			</footer>

</div>
</body>
</html>

graduators/templates/graduators/graduatordetails.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>graduator </title>


    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'graduators/graduatordeatils/bootstrap.min.css' %}">
    <link href="{% static 'graduators/graduatordeatils/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'graduators/graduatordeatils/profile.css' %}" rel="stylesheet">
  </head>
  <body>


        <!-- nav bar -->

        <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <a href="mail-compose.html" class="btn btn-danger btn-block btn-compose-email">Compose Email</a>
                <ul class="nav nav-pills nav-stacked nav-email shadow mb-20">
                    <li class="active"> <a href="#mail-inbox.html"> <i class="fa fa-inbox"></i> Inbox  <span class="label pull-right">7</span> </a> </li>

                    <li> <a href="#"><i class="fa fa-certificate"></i> Important</a> </li>

                </ul><!-- /.nav -->

                <h5 class="nav-email-subtitle">More</h5>
                <ul class="nav nav-pills nav-stacked nav-email mb-20 rounded shadow">
                    <li> <a href="#"> <i class="fa fa-folder-open"></i> Promotions  <span class="label label-danger pull-right">3</span> </a> </li>

                </ul><!-- /.nav -->
            </div>
            <div class="col-sm-9">

                <!-- resumt -->
                <div class="panel panel-default">
                       <div class="panel-heading resume-heading">
                          <div class="row">
                             <div class="col-lg-12">
                                <div class="col-xs-12 col-sm-4">
                                   <figure>
                                      <img class="img-circle img-responsive" alt="" src="{{kaka.image.url}}">
                                   </figure>
                                   <div class="row">
                                      <div class="col-xs-12 social-btns">

                                         <div class="col-xs-3 col-md-1 col-lg-1 social-btn-holder">
                                            <a href="#" class="btn btn-social btn-block btn-twitter">
                                            <i class="fa fa-twitter"></i> </a>
                                         </div>
                                         <div class="col-xs-3 col-md-1 col-lg-1 social-btn-holder">
                                            <a href="#" class="btn btn-social btn-block btn-linkedin">
                                            <i class="fa fa-linkedin"></i> </a>
                                         </div>
                                         <div class="col-xs-3 col-md-1 col-lg-1 social-btn-holder">
                                            <a href="#" class="btn btn-social btn-block btn-github">
                                            <i class="fa fa-github"></i> </a>
                                         </div>
                                         <div class="col-xs-3 col-md-1 col-lg-1 social-btn-holder">
                                            <a href="#" class="btn btn-social btn-block btn-stackoverflow">
                                            <i class="fa fa-stack-overflow"></i> </a>
                                         </div>
                                      </div>


                                   </div>
                                </div>
                                <div class="col-xs-12 col-sm-8">
                                   <ul class="list-group">
                                      <li class="list-group-item">{{kaka}}</li>
                                      <li class="list-group-item">Software Engineer</li>
                                      <li class="list-group-item">Google Inc. </li>
                                      <li class="list-group-item"><i class="fa fa-phone"></i> {{kaka.phone}} </li>
                                      <li class="list-group-item"><i class="fa fa-envelope"></i> {{ kaka.email }}</li>
                                   </ul>
                                </div>
                             </div>
                          </div>
                       </div>
                       <div class="bs-callout bs-callout-danger">
                          <h4>Summary</h4>
                          <p>
                            {{kaka.PersonalDescription}}
                          </p>
                          <p>
                             Achievements or Accomplishments while at school
                          </p>
                       </div>
                       <div class="bs-callout bs-callout-danger">
                          <h4>Research Interests</h4>
                          <p>
                             Software Engineering, Machine Learning, Image Processing,
                             Computer Vision, Artificial Neural Networks, Data Science,
                             Evolutionary Algorithms.
                          </p>
                       </div>
                       <div class="bs-callout bs-callout-danger">
                          <h4>Prior Experiences</h4>
                          <ul class="list-group">
                             <a class="list-group-item inactive-link" href="#">
                                <h4 class="list-group-item-heading"> Software Engineer at Twitter </h4>
                                <p class="list-group-item-text">
                                   Lorem ipsum dolor sit amet, ea vel prima adhuc, scripta liberavisse ea quo, te vel vidit mollis complectitur. Quis verear mel ne. Munere vituperata vis cu,
                                   te pri duis timeam scaevola, nam postea diceret ne. Cum ex quod aliquip mediocritatem, mei habemus persecuti mediocritatem ei.
                                </p>
                             </a>

                          </ul>
                       </div>
                       <div class="bs-callout bs-callout-danger">
                          <h4>Key Expertise</h4>
                          <ul class="list-group">
                             <li class="list-group-item"> Back-end Development with Python </li>

                          </ul>
                       </div>

                       <div class="bs-callout bs-callout-danger">
                          <h4>Education</h4>
                          <table class="table table-striped table-responsive ">
                             <thead>
                                <tr>
                                   <th>Degree</th>
                                   <th>Graduation Year</th>
                                   <th>CGPA</th>
                                </tr>
                             </thead>
                             <tbody>

                                <tr>
                                   <td>Diploma. in Information Technology</td>
                                   <td>2017</td>
                                   <td> 3.5 </td>
                                </tr>
                             </tbody>
                          </table>
                       </div>
                    </div>
                 </div>
                <!-- resume -->

            </div>
        </div>
        </div>



<!--
    <h3>The details of the graduator  will be on this page</h3>
    </p>
    <small>waiting for the designed page from the designer</small> <br>

    </p>
    Hello there,We are glad that you are here.if you are interested in hiring,employing or interview <b>{{kaka}},</b>please feel free to <br>
    reach him out through his contacts listed

    <h6>{{ kaka.adress }}</h6>
    <h6></h6>


    {% if kaka.portfolio_set.all %}
    <ul>
      {% for portfolio in kaka.portfolio_set.all %}
        <li>{{ portfolio.projectTitle }}</li>
      {% endfor %}
    </ul>

    {% else %}
      <h3>The graduator doesnt have any portfolio</h3>
    {% endif %}


-->
  </body>
</html>

graduators/templates/graduators/graduatorsmanifest1.html
<!DOCTYPE html>
		<html>
				<head>
					{% load staticfiles %}
					<!-- Latest compiled and minified CSS -->
            <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

          <!-- jQuery library -->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

          <!-- Latest compiled JavaScript -->
            <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

            <link rel="stylesheet" type="text/css" href="{% static 'graduators/styles/bootstrap/bootstrap.min.css' %}" />
					  <link rel="stylesheet" type="text/css" href="{% static 'graduators/styles/css/index.css %}" />

				</head>
				<body>

					<div class="container-fluid">

							<header>
									<nav class="navbar container-fluid">
											<div class="container-fluid">
														<div class="navbar-header">
																<span class="navbar-brand"><a href="">FISPY</a></span>
														</div>

														<ul class="nav navbar-nav navbar-right">
															<li><a href="#">Graduator</a></li>
															<li><a href="#">Event</a></li>
															<li><a href="#">Sign in	</a></li>
														</ul>
											</div>
									</nav>
							</header>
						</div>



            <div class="container">
                <div class="row">
									{% for graduator in all_graduators %}
                    <div class="col-xs-12 col-sm-6 col-md-4">
                        <div class="well well-sm">
                            <div class="row">

                                <div class="col-sm-6 col-md-4">
                                    <img src="#" alt="" class="img-rounded img-responsive" />
                                </div>
                                <div class="col-sm-6 col-md-8">
                                    <h3>{{graduator.FullName}}</h3>
                                    <h4>{{graduator.adress}}</h4>
                                    <p>
                                        <i>{{graduator.email}}<br />
                                        <i></i><a href="http://www.jquery2dotnet.com">{{graduator.phone}}</a><br />
                                        <i></i>{{graduator.graduationYear}}</p>
                                    <!-- Split button
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-primary">Social</button>
                                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                            <span class="caret"></span><span class="sr-only">Social</span>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="#">Twitter</a></li>
                                            <li><a href="https://plus.google.com/+Jquery2dotnet/posts">Google +</a></li>

                                            <li class="divider"></li>
                                            <li><a href="#">Github</a></li>
                                        </ul>
                                    </div>
																		-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
						{% endfor %}
<!--   footer
						<footer>
								<nav class="navbar navbar-fixed-bottom" >

										<span>SUZA DIT Final Year Project 2017</span>
										<div class="about"> <span> <a href="#">Contact</a>

												</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
												<span><a href="#">About</a></span>
										</div>
								</nav>
						</footer>

						 -->


</body>
</html>

graduators/templates/graduators/graduatorsmanifest2LTS.html
<!DOCTYPE html>
		<html>
				<head>
            <link rel="stylesheet" type="text/css" href="bootstrap/bootstrap.min.css">
					  <link rel="stylesheet" type="text/css" href="/css/index.css">
						<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
				</head>
				<body>

					<div class="container-fluid">

							<header>
									<nav class="navbar container-fluid">
											<div class="container-fluid">
														<div class="navbar-header">
																<span class="navbar-brand"><a href="">FISPY</a></span>
														</div>

														<ul class="nav navbar-nav navbar-right">
															<li><a href="#">Graduator</a></li>
															<li><a href="#">Event</a></li>
															<li><a href="#">Sign in	</a></li>
														</ul>
											</div>
									</nav>
							</header>
						</div>



            <div class="container">
                <div class="row">
									{% for graduator in all_graduators %}
                    <div class="col-xs-12 col-sm-6 col-md-4">
                        <div class="well well-sm">
                            <div class="row">

                                <div class="col-sm-6 col-md-4">
                                    <img src="#" alt="" class="img-rounded img-responsive" />
                                </div>
                                <div class="col-sm-6 col-md-8">
                                    <h3>{{graduator.FullName}}</h3>
                                    <h4>{{graduator.adress}}</h4>
                                    <p>
                                        <i>{{graduator.email}}<br /></i>
                                        <a href="http://www.jquery2dotnet.com">{{graduator.phone}}</a><br />
                                        {{graduator.graduationYear}}</p>
                                    <!-- Details button
																	-->
                                </div>
                            </div>
                        </div>
                    </div>
										{% endfor %}
                </div>
            </div>

<!--   footer
									-->


</body>
</html>

graduators/templates/graduators/graduatorsmanifest3.html
<!DOCTYPE html>
{% load staticfiles %}
		<html>
				<head>
            <link rel="stylesheet" type="text/css" href="{% static 'graduators/styles/bootstrap.min.css' %}">
					  <link rel="stylesheet" type="text/css" href="{% static 'graduators/index.css' %}">
						<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
				</head>
				<body>

					<div class="container-fluid">

							<header>
									<nav class="navbar container-fluid">
											<div class="container-fluid">
														<div class="navbar-header">
																<span class="navbar-brand"><a href="">FISPY</a></span>
														</div>

														<ul class="nav navbar-nav navbar-right">
															<li><a href="#">Graduator</a></li>
															<li><a href="#">Event</a></li>
															<li><a href="#">Sign in	</a></li>
														</ul>
											</div>
									</nav>
							</header>
						</div>



            <div class="container">
                <div class="row">
									{% for graduator in all_graduators %}
                    <div class="col-xs-12 col-sm-6 col-md-4">
                        <div class="well well-sm">
                            <div class="row">

                                <div class="col-sm-6 col-md-4">
                                    <img src="{{graduator.image.url}}" alt="" class="img-rounded img-responsive" />
                                </div>
                                <div class="col-sm-6 col-md-8">
                                    <a href="{{graduator.id}}"><h3>{{graduator.FullName}}</h3></a>
                                    <h4>{{graduator.adress}}</h4>
                                    <p>
                                        <i>{{graduator.email}}<br /></i>
                                        {{graduator.phone}}<br />
                                        {{graduator.graduationYear}}</p>
                                    <!-- Details button
																	-->
                                </div>
                            </div>
                        </div>
                    </div>
										{% endfor %}
                </div>
            </div>

<!--   footer
									-->


</body>
</html>

graduators/templates/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>hellow</title>
  </head>
  <body>
    <h1>this is the default homepage</h1>
  </body>
</html>